import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Search, ArrowUpRight, Building2, FileText, Plus, Bookmark, Check, Link2, LockKeyhole } from 'lucide-react';
import { useWorkspace } from '../../lib/store';
import { Button, CompanyMark, EmptyState, ExternalJobLink, JobBadge, Note, PageHeading, Tag } from '../../components/ui';

const RESEARCH_PROMPT = '## 업무와 역할\n- 실제 담당 업무와 팀 구성:\n- 가장 확인하고 싶은 질문:\n\n## 근무 조건\n- 근무 장소와 외근·상주 여부:\n- 고용 형태와 보상 조건:\n\n## 지원한 이유\n- 내 경험과 연결되는 부분:\n- 직접 확인한 정보와 출처:\n';
export default function Companies() {
  const { state, update, notify } = useWorkspace();
  const [params, setParams] = useSearchParams();
  const [query, setQuery] = useState('');
  const companies = [...new Set(state.jobs.map(j => j.company))].filter(c => c.toLowerCase().includes(query.toLowerCase()));
  const [selected, setSelected] = useState(params.get('company') ?? companies[0] ?? '');
  const [tab, setTab] = useState('notes');
  useEffect(() => { const name = params.get('company'); if (name) setSelected(name); }, [params]);
  const name = companies.includes(selected) ? selected : companies[0];
  const jobs = state.jobs.filter(j => j.company === name);
  const company = jobs[0];
  const applications = state.applications.filter(a => a.jobSnapshot.company === name);
  const note = state.companyNotes[name] ?? '';
  const setNote = (value: string) => update(s => ({ ...s, companyNotes: { ...s.companyNotes, [name]: value } }));
  const addPrompt = () => { if (note.includes('## 업무와 역할')) { notify('이 질문 틀은 이미 메모에 있어요.'); return; } setNote(note ? `${note}\n\n${RESEARCH_PROMPT}` : RESEARCH_PROMPT); notify('기업을 알아볼 때 확인할 질문 틀을 넣었어요.'); };
  return <div className="page-enter companies-page"><PageHeading eyebrow="KNOW WHERE YOU ARE GOING" title="지원할 회사를 더 알아가는 시간" description="공고 속 정보와 직접 조사한 메모를 구분해서, 회사마다 차곡차곡."/><div className="companies-layout"><aside className="company-directory"><label className="search-input"><Search size={16}/><input aria-label="기업 검색" placeholder="보관한 회사 검색" value={query} onChange={e => setQuery(e.target.value)}/></label><span className="directory-count">{companies.length}개의 회사</span>{companies.map(c => { const job = state.jobs.find(j => j.company === c)!; return <button className={`company-directory-item ${name === c ? 'selected' : ''}`} key={c} onClick={() => { setSelected(c); setParams({ company: c }); }}><CompanyMark job={job} small/><div><strong>{c}</strong><span>공고 {state.jobs.filter(j => j.company === c).length}개{job.isDemo ? ' · 가상 기업' : ''}</span></div>{state.companyNotes[c] && <FileText size={14}/>}</button>; })}{!companies.length && <EmptyState title="보관한 회사가 없어요" description="공고를 저장하면 회사별 노트가 생겨요."/>}</aside>
    {company ? <section className="company-workspace"><div className="company-profile-header"><CompanyMark job={company}/><div><p className="eyebrow">COMPANY NOTES</p><h2>{name}</h2><span>{company.isDemo ? '가상 예시 기업 · 실제 기업 분석이 아니에요' : '내가 보관한 공고에서 만든 기업 공간'}</span></div><div className="company-profile-stats"><span><strong>{jobs.length}</strong>보관 공고</span><span><strong>{applications.length}</strong>지원 기록</span></div></div><div className="detail-tabs" role="tablist" aria-label="기업 정보">{[{ id: 'notes', label: '조사 메모' }, { id: 'info', label: '공고 속 회사 정보' }, { id: 'jobs', label: '보관한 공고' }].map(t => <button key={t.id} role="tab" aria-selected={tab === t.id} className={tab === t.id ? 'active' : ''} onClick={() => setTab(t.id)}>{t.label}</button>)}</div><div className="company-tab-content" role="tabpanel">{tab === 'notes' && <><div className="company-note-toolbar"><h3>기억해둘 회사 이야기</h3><Button onClick={addPrompt}><Plus size={14}/>질문 틀 넣기</Button></div><label className="sr-only" htmlFor="company-research-note">기업 조사 메모</label><textarea id="company-research-note" className="company-notes-textarea" value={note} maxLength={20000} onChange={e => setNote(e.target.value)} placeholder="회사에 대해 직접 알아본 내용, 면접 때 확인할 점, 내 경험과 맞닿은 부분을 적어보세요. 정보의 출처도 함께 남기면 좋아요."/><div className="split-line"><span className="local-note"><LockKeyhole size={13}/>이 브라우저에 자동 저장</span><span className="field-hint">{note.length.toLocaleString()}자</span></div><div className="research-checks"><p>이런 점을 확인해보세요</p><div><span>실제 업무 범위</span><span>근무·보상 조건</span><span>함께 일할 팀</span><span>내가 기여할 경험</span></div></div></>}
    {tab === 'info' && <><Tag>공고에 기록된 내용</Tag><h3 className="subsection-heading">회사 소개</h3><div className="prose-text">{company.companyInfo || '공고에서 별도로 정리한 회사 소개가 없어요. 원문을 확인하거나 조사 메모에 직접 남겨주세요.'}</div><h3 className="subsection-heading">공고에 기재된 근무 환경</h3><div className="prose-text">{company.benefits || '별도로 기재한 근무 환경이 없어요.'}</div><div className="company-information-source"><Link2 size={17}/><div><strong>정보 출처</strong><span>{company.source}{company.isDemo ? ' · 가상 예시' : ''}</span></div><ExternalJobLink job={company}/></div><Note tone="orange">직원 수, 매출, 평판 등을 자동으로 수집하거나 추정하지 않아요. 회사 소개의 내용과 최신 여부는 출처에서 직접 확인해주세요.</Note></>}
    {tab === 'jobs' && <div className="company-saved-jobs">{jobs.map(job => <Link key={job.id} to={`/app/jobs?job=${job.id}`}><div><h3>{job.title}</h3><p>{job.location} · {job.experience} · {job.employment}</p><div className="tag-row">{job.skills.slice(0, 4).map(s => <Tag key={s}>{s}</Tag>)}</div></div><div><JobBadge job={job}/><ArrowUpRight size={19}/></div></Link>)}</div>}</div></section> : <div className="panel"><EmptyState title="다음에 만날 회사를 모아보세요" description="공고 탐색에서 기업을 보관하면 조사 메모를 시작할 수 있어요." action={<Link to="/app/jobs" className="button primary">공고 탐색<ArrowUpRight size={16}/></Link>}/></div>}</div></div>;
}
