import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Bookmark, FolderOpen, MessageCircle, Send, Plus, CalendarDays, Check, Compass, ShieldCheck } from 'lucide-react';
import { useWorkspace } from '../../lib/store';
import { formatDate, latestDocuments, matchJob, STAGES } from '../../lib/domain';
import { CompanyMark, EmptyState, JobBadge, SectionTitle, Tag, TextArrow, effectiveStatus } from '../../components/ui';
import Mascot from '../../components/Mascot';

export default function Dashboard() {
  const { state } = useWorkspace();
  const live = state.applications.filter(a => !['offer', 'closed'].includes(a.stage));
  const saved = state.jobs.filter(j => j.saved);
  const documents = latestDocuments(state.documents);
  const interviews = state.applications.filter(a => a.stage === 'interview');
  const upcoming = [...interviews].filter(a => a.interviewAt).sort((a, b) => a.interviewAt.localeCompare(b.interviewAt));
  const recommendations = [...state.jobs].filter(j => effectiveStatus(j) !== 'closed' && !matchJob(j, state.profile).excluded.length).sort((a, b) => matchJob(b, state.profile).matched.length - matchJob(a, state.profile).matched.length).slice(0, 3);
  const weekCount = state.applications.filter(a => a.submissions.some(s => Date.now() - new Date(s.createdAt).getTime() < 7 * 86400000 && Date.now() >= new Date(s.createdAt).getTime())).length;
  const progress = Math.min(100, weekCount / Math.max(1, state.profile.weeklyGoal) * 100);
  const stats = [{ label: '관심 공고', value: saved.length, sub: '다시 살펴볼 자리', icon: Bookmark, url: '/app/jobs?saved=1' }, { label: '진행 중인 지원', value: live.length, sub: '한 단계씩 준비 중', icon: Send, url: '/app/applications' }, { label: '면접 준비', value: interviews.length, sub: '내 이야기로 준비하기', icon: MessageCircle, url: '/app/interview' }, { label: '내 서류', value: documents.length, sub: '제출본까지 차곡차곡', icon: FolderOpen, url: '/app/documents' }];
  return <div className="dashboard page-enter">
    <div className="dashboard-greeting"><div><p className="eyebrow">YOUR NEXT CHAPTER</p><h1>나의 다음 자리, 한눈에.</h1></div><span className="today-label"><CalendarDays size={15}/>{new Date().toLocaleDateString('ko-KR', { month: 'long', day: 'numeric', weekday: 'long' })}</span></div>
    <section className="dashboard-hero"><div className="dashboard-hero-copy"><span className="hero-mini-label"><span/>작은 준비가 쌓이는 공간</span><h2>흩어져 있던 준비를,<br/><em>하나의 가능성으로.</em></h2><p>좋은 공고는 놓치지 않고, 내 이야기는 잊지 않도록.<br className="desktop-only"/>공고부터 면접까지 한곳에 모아보세요.</p><Link to="/app/jobs" className="button primary">다음 자리 찾아보기<ArrowUpRight size={17}/></Link></div><div className="dashboard-hero-art"><span className="hero-orbit orbit-one"/><span className="hero-orbit orbit-two"/><span className="tiny-orbit-card card-a"><Bookmark size={14}/>나에게 맞는 공고</span><Mascot className="dashboard-mascot"/><span className="tiny-orbit-card card-b"><Check size={14}/>제출한 그대로 기억</span></div><div className="hero-bottom-strip"><span><ShieldCheck size={14}/>내 기기에 저장</span><span>계정 없이 시작</span><span>오픈소스로 함께</span></div></section>
    {state.demo && <div className="demo-banner"><span className="demo-pill">샘플 공간</span><p>지금 보이는 기업·공고·제출자료는 모두 가상 예시예요. 실제 공고도 직접 추가할 수 있어요.</p><Link to="/app/settings">내 자료로 시작<ArrowRight size={14}/></Link></div>}
    <section className="stats-strip" aria-label="나의 준비 현황">{stats.map(s => <Link key={s.label} to={s.url} className="stat-item"><div className="stat-label"><s.icon size={16}/>{s.label}<ArrowUpRight size={13}/></div><div className="stat-value">{s.value}<span>{s.label === '면접 준비' || s.label === '진행 중인 지원' ? '건' : '개'}</span></div><span className="stat-sub">{s.sub}</span></Link>)}</section>
    <div className="dashboard-columns"><div className="dashboard-primary"><section className="panel recommendation-panel"><SectionTitle title="내 경험과 맞닿은 공고" meta="프로필에 등록한 기술을 기준으로 정리했어요" action={<Link className="text-link" to="/app/jobs"><TextArrow>모두 보기</TextArrow></Link>}/>{recommendations.length ? recommendations.map(job => { const match = matchJob(job, state.profile); return <Link key={job.id} className="recommended-job" to={`/app/jobs?job=${job.id}`}><CompanyMark job={job}/><div className="recommended-job-main"><div className="company-line"><span>{job.company}</span>{job.isDemo && <span className="demo-inline">가상 기업</span>}</div><h3>{job.title}</h3><div className="job-meta">{job.location}<span>·</span>{job.experience}<span>·</span>{job.employment}</div><div className="tag-row">{job.skills.slice(0, 3).map(skill => <Tag key={skill} tone={match.matched.includes(skill) ? 'blue' : 'neutral'}>{skill}</Tag>)}</div></div><div className="recommended-job-side"><JobBadge job={job}/><ArrowUpRight size={20}/></div></Link>; }) : <EmptyState title="조건에 맞는 공고를 모아보세요" description="공고를 추가하거나 설정에서 관심 기술을 바꾸면 여기에 나타나요." action={<Link to="/app/jobs" className="button secondary">공고 탐색<Compass size={15}/></Link>}/>}</section>
      <section className="panel"><SectionTitle title="이어가던 준비" action={<Link className="text-link" to="/app/applications"><TextArrow>지원 현황</TextArrow></Link>}/>{state.applications.length ? <div className="recent-applications">{state.applications.slice(0, 3).map(a => <Link key={a.id} to={`/app/applications?application=${a.id}`}><CompanyMark job={a.jobSnapshot} small/><div><strong>{a.jobSnapshot.company}</strong><span>{a.jobSnapshot.title}</span></div><Tag tone={a.stage === 'interview' ? 'blue' : a.stage === 'offer' ? 'green' : 'neutral'}>{STAGES.find(s => s.id === a.stage)?.label}</Tag><ChevronArrow/></Link>)}</div> : <EmptyState title="첫 번째 지원을 시작해보세요" description="공고에서 ‘지원 준비’를 누르면 회사별 준비 공간이 생겨요."/>}</section></div>
      <aside className="dashboard-secondary"><section className="panel next-step-panel"><SectionTitle title="다음 일정" action={<CalendarDays size={18} className="muted"/>}/>{upcoming.length ? upcoming.slice(0, 2).map(a => <div className="upcoming-item" key={a.id}><div className="calendar-tile"><span>{new Date(a.interviewAt).toLocaleDateString('ko-KR', { month: 'short' })}</span><strong>{new Date(a.interviewAt).getDate()}</strong></div><div><span className="eyebrow small">INTERVIEW{a.isDemo ? ' / 예시' : ''}</span><h3>{a.jobSnapshot.company}</h3><p>{formatDate(a.interviewAt)}</p><Link to={`/app/interview?application=${a.id}`} className="text-link">면접 준비하기<ArrowRight size={14}/></Link></div></div>) : <div className="quiet-empty"><CalendarDays size={25}/><p>정해진 일정이 없어요.</p><Link to="/app/applications" className="text-link">지원 기록에서 추가하기</Link></div>}</section>
      <section className="weekly-goal"><div className="weekly-goal-top"><span className="eyebrow">MY OWN PACE</span><Link to="/app/settings" aria-label="지원 목표 설정"><ArrowUpRight size={17}/></Link></div><h3>내 속도로, 꾸준하게.</h3><p>최근 7일 제출한 지원</p><div className="weekly-number">{weekCount}<span>/ {state.profile.weeklyGoal}건</span></div><div className="progress-track" role="progressbar" aria-label="최근 7일 지원 목표" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress)}><span style={{ width: `${progress}%` }}/></div><p className="weekly-footnote">{weekCount >= state.profile.weeklyGoal ? '설정한 목표에 도달했어요.' : `목표까지 ${Math.max(0, state.profile.weeklyGoal - weekCount)}건 남았어요.`}</p></section>
      <Link to="/app/documents" className="quick-document"><div className="quick-document-icon"><Plus size={20}/></div><div><strong>내 서류 한 장부터</strong><span>이력서·자소서·포트폴리오 보관</span></div><ArrowUpRight size={18}/></Link></aside></div>
  </div>;
}
function ChevronArrow() { return <ArrowUpRight size={15} className="muted"/>; }
