import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { UserRound, SlidersHorizontal, LockKeyhole, Download, Upload, Database, CircleHelp, ArrowUpRight, Save, RotateCcw, Trash2, Plug, Check, ShieldCheck, FolderOpen } from 'lucide-react';
import { useWorkspace } from '../../lib/store';
import { createDemoState, createEmptyState } from '../../lib/seed';
import { exportBackup, readBackupFile } from '../../lib/files';
import type { WorkspaceState } from '../../lib/types';
import { Button, ConfirmDialog, Modal, Note, PageHeading, Tag } from '../../components/ui';

export default function Settings() {
  const { state, update, storageStatus, notify } = useWorkspace();
  const [profile, setProfile] = useState(state.profile);
  const [skills, setSkills] = useState(state.profile.skills.join(', '));
  const [locations, setLocations] = useState(state.profile.locations.join(', '));
  const [excluded, setExcluded] = useState(state.profile.excludeKeywords.join(', '));
  const [reset, setReset] = useState<'empty' | 'demo' | null>(null);
  const [pending, setPending] = useState<WorkspaceState | null>(null);
  const [importing, setImporting] = useState(false);
  const [integration, setIntegration] = useState(false);
  const input = useRef<HTMLInputElement>(null);
  useEffect(() => { setProfile(state.profile); setSkills(state.profile.skills.join(', ')); setLocations(state.profile.locations.join(', ')); setExcluded(state.profile.excludeKeywords.join(', ')); }, [state.profile]);
  const list = (value: string, max: number) => [...new Set(value.split(',').map(s => s.trim()).filter(Boolean))].slice(0, max);
  const saveProfile = (e: FormEvent) => { e.preventDefault(); update(s => ({ ...s, profile: { ...profile, name: profile.name.trim() || '나의 워크스페이스', role: profile.role.trim(), skills: list(skills, 24), locations: list(locations, 12), excludeKeywords: list(excluded, 20), weeklyGoal: Math.max(1, Math.min(50, Number(profile.weeklyGoal) || 5)) } })); notify('내 프로필과 선호 조건을 반영했어요.'); };
  const backup = () => { try { exportBackup(state); notify('백업 파일 다운로드를 시작했어요. 내 서류 원본도 포함돼요.'); } catch (error) { notify(error instanceof Error ? error.message : '백업을 만들지 못했어요.'); } };
  const readBackup = async (file: File) => { setImporting(true); try { setPending(await readBackupFile(file)); } catch (error) { notify(error instanceof Error ? error.message : '백업을 읽지 못했어요.'); } finally { setImporting(false); if (input.current) input.current.value = ''; } };
  return <div className="page-enter settings-page"><PageHeading eyebrow="MAKE YOURSELF AT HOME" title="내게 맞는 준비 공간" description="관심 기술부터 데이터 보관까지, 내가 정하고 내가 관리해요."/><div className="settings-columns"><div className="settings-primary"><section className="panel settings-section"><div className="settings-section-title"><span className="settings-icon"><UserRound size={20}/></span><div><h2>내 프로필과 관심 조건</h2><p>공고 비교에 쓰는 정보예요. 회사에는 공개되지 않아요.</p></div></div><form className="stack-form" onSubmit={saveProfile}><div className="form-grid"><label>공간 이름<input value={profile.name} maxLength={40} onChange={e => setProfile(p => ({ ...p, name: e.target.value }))} placeholder="나의 워크스페이스" required/></label><label>희망 직무<input value={profile.role} maxLength={80} onChange={e => setProfile(p => ({ ...p, role: e.target.value }))} placeholder="예: 백엔드 개발"/></label></div><label>내가 경험한 기술<span className="field-hint">쉼표로 구분해요. 이 목록과 공고의 요구 기술을 직접 비교해요.</span><input value={skills} maxLength={500} onChange={e => setSkills(e.target.value)} placeholder="Python, FastAPI, SQL, Docker"/></label><label>관심 지역<input value={locations} maxLength={300} onChange={e => setLocations(e.target.value)} placeholder="서울, 경기, 원격"/></label><label>추천에서 제외할 키워드<span className="field-hint">대시보드 추천에서 제외돼요. 공고 탐색에서는 원문을 그대로 볼 수 있어요.</span><input value={excluded} maxLength={500} onChange={e => setExcluded(e.target.value)} placeholder="예: 인턴, 상주"/></label><label className="goal-field">최근 7일 지원 목표<div><input type="number" min={1} max={50} value={profile.weeklyGoal} onChange={e => setProfile(p => ({ ...p, weeklyGoal: Number(e.target.value) }))}/><span>건</span></div></label><div className="form-actions"><Button type="submit" variant="primary"><Save size={16}/>프로필 저장</Button></div></form></section>
      <section className="panel settings-section"><div className="settings-section-title"><span className="settings-icon"><Database size={20}/></span><div><h2>내 자료 보관과 백업</h2><p>원본 서류와 제출 기록까지, 하나의 파일로 가져갈 수 있어요.</p></div><Tag tone={storageStatus === 'saved' ? 'green' : 'orange'}>{storageStatus === 'saved' ? '기기에 저장됨' : storageStatus === 'saving' ? '저장 중' : '저장 상태 확인 필요'}</Tag></div><div className="backup-summary"><span><strong>{state.jobs.length}</strong>보관 공고</span><span><strong>{state.documents.length}</strong>서류 버전</span><span><strong>{state.applications.length}</strong>지원 기록</span><span><strong>{state.practice.length}</strong>연습 답변</span></div><Note tone="orange"><strong>브라우저 데이터 삭제 = 내 자료 삭제.</strong><br/>다른 기기로 자동 동기화되지 않아요. 중요한 서류를 넣었다면 백업을 꼭 내려받아주세요.</Note><div className="backup-actions"><Button onClick={backup}><Download size={17}/>전체 백업 내려받기</Button><Button onClick={() => input.current?.click()} disabled={importing}><Upload size={17}/>{importing ? '백업 확인 중' : '백업 파일 불러오기'}</Button><input type="file" accept=".json,application/json" ref={input} className="sr-only" aria-label="백업 파일 선택" onChange={e => e.target.files?.[0] && void readBackup(e.target.files[0])}/></div><p className="field-hint">JSON 파일 · 원본 서류와 음성 답변 포함 · 암호화되지 않으므로 안전한 곳에 보관해주세요.</p></section>
      <section className="panel settings-section"><div className="settings-section-title"><span className="settings-icon"><Plug size={20}/></span><div><h2>자동화·AI 연결 상태</h2><p>현재 되는 일과 아직 연결되지 않은 일을 구분해요.</p></div></div><div className="integration-rows"><button onClick={() => setIntegration(true)}><div className="integration-icon">J</div><div><strong>실제 채용공고 조회</strong><span>원티드 공개 조회 · 사람인은 서버 API 키 설정 시 사용</span></div><Tag tone="blue">조회 기능 제공</Tag><ArrowUpRight size={16}/></button><button onClick={() => setIntegration(true)}><div className="integration-icon"><MessageIcon/></div><div><strong>AI 글쓰기·면접 코칭</strong><span>현재는 직접 편집, 제출본 근거의 규칙 기반 연습</span></div><Tag>미연결</Tag><ArrowUpRight size={16}/></button></div><div className="enabled-feature"><Check size={16}/><span>별도 계정이나 API 키 없이 서류 관리·제출본 보관·연습 기록을 사용할 수 있어요.</span></div></section>
      <section className="panel settings-section reset-section"><h2>워크스페이스 다시 시작</h2><p>이 브라우저의 준비 공간만 초기화해요. 먼저 백업 파일을 내려받아주세요.</p><div><Button onClick={() => setReset('demo')}><RotateCcw size={15}/>가상 예시로 다시 보기</Button><Button variant="danger" onClick={() => setReset('empty')}><Trash2 size={15}/>비우고 내 자료로 시작</Button></div></section>
    </div><aside className="settings-aside"><div className="privacy-poster"><div className="privacy-seal"><LockKeyhole size={36} strokeWidth={1.4}/><span/></div><span className="eyebrow">YOUR DATA, YOUR PLACE.</span><h2>내 이야기는<br/>내가 지켜요.</h2><p>계정도, 서버 업로드도 없이.<br/>기본 저장 공간은 지금 사용하는<br/>브라우저의 IndexedDB예요.</p><div><Check size={14}/>파일 원본도 로컬에 보관</div><div><Check size={14}/>제출본 버전을 따로 기억</div><div><Check size={14}/>백업으로 다른 기기에 이동</div><small>브라우저 저장소 자체는 암호화 보관함이 아니에요. 공용 기기에서는 개인정보를 넣지 않는 편이 좋아요.</small></div><Link to="/" className="about-product-link"><span>JariZip이 처음이라면</span><strong>제품 소개 둘러보기<ArrowUpRight size={17}/></strong></Link><a className="about-product-link" href="https://github.com/Blue-B/JariZip/issues" target="_blank" rel="noreferrer"><span>불편한 점이 있나요?</span><strong>오픈소스에 의견 남기기<ArrowUpRight size={17}/></strong></a></aside></div>
    {reset && <ConfirmDialog title={reset === 'empty' ? '비우고 내 자료로 시작할까요?' : '가상 예시로 교체할까요?'} description="현재 공고, 서류 원본, 지원 기록, 음성 답변과 프로필이 모두 교체돼요. 백업 파일이 없으면 되돌릴 수 없어요. 예시 파일이 아니라 직접 올린 자료가 있다면 먼저 백업해주세요." confirmLabel={reset === 'empty' ? '비우고 시작' : '예시로 교체'} danger onClose={() => setReset(null)} onConfirm={() => { const next = reset === 'empty' ? createEmptyState() : createDemoState(); update(() => next); setReset(null); notify('워크스페이스 데이터를 교체했어요.'); }}/>} {pending && <ConfirmDialog title="이 백업으로 내 공간을 교체할까요?" description={`파일을 검사했어요. 공고 ${pending.jobs.length}개, 서류 ${pending.documents.length}개 버전, 지원 기록 ${pending.applications.length}건이 들어 있어요. 불러오면 현재 데이터와 합치지 않고 전체 교체해요. 먼저 현재 공간을 백업해주세요.`} confirmLabel="백업으로 교체" onClose={() => setPending(null)} onConfirm={() => { update(() => pending); setPending(null); notify('검사한 백업 데이터를 불러왔어요.'); }}/>} {integration && <Modal title="현재 연결 범위" onClose={() => setIntegration(false)}><Note tone="blue">채용 탐색에서 실제 공고를 조회합니다. 원티드는 공개 응답을 읽으며 공식 제휴 API는 아닙니다. AI 글쓰기·평가는 아직 연결하지 않았어요.</Note><div className="integration-explanation"><h3>공고</h3><p>검색·본문 조회·보관·지원 준비가 연결돼요. 조회 시각과 출처의 접수 상태를 기록하며 실패를 가상 공고로 대신하지 않습니다. 직접 본 공고를 수동으로 보관하는 기능도 유지합니다.</p><h3>면접·서류</h3><p>제출한 문서에서 문장을 찾아 정해진 규칙으로 질문을 만들어요. AI가 읽고 판단한 것처럼 표시하지 않아요. 서류 템플릿과 편집기는 바로 사용할 수 있어요.</p><h3>연결 조건과 개인정보</h3><p>npm start 또는 npm run dev로 공고 조회 서버를 함께 실행해주세요. 사람인은 서버 .env.local에 SARAMIN_ACCESS_KEY가 필요합니다. 검색어와 지역만 출처로 전송하고, 이력서·녹음·지원 기록은 전송하지 않아요.</p></div><div className="form-actions"><Button variant="primary" onClick={() => setIntegration(false)}>확인했어요</Button></div></Modal>}</div>;
}
function MessageIcon() { return <CircleHelp size={21}/>; }
