import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Check, FileText, PencilLine, Layers3, LockKeyhole } from 'lucide-react';
import { DOCUMENT_TEMPLATES } from '../../lib/seed';
import type { DocumentTemplate } from '../../lib/types';
import { Button, Modal, Note, PageHeading, Tag } from '../../components/ui';
import DocumentEditor, { DocumentPaper } from '../../components/DocumentEditor';

export default function Templates() {
  const [editing, setEditing] = useState<DocumentTemplate | null>(null);
  const [preview, setPreview] = useState<DocumentTemplate | null>(null);
  const navigate = useNavigate();
  return <div className="page-enter templates-page"><PageHeading eyebrow="A PLACE TO BEGIN" title="빈 페이지가 막막할 때" description="구조는 빌리고, 내용은 내 경험으로. 한국어 취업 서류를 위한 시작점이에요."/><section className="template-intro"><div><span className="eyebrow">LESS BLANK. MORE YOU.</span><h2>잘 꾸민 문장보다,<br/><em>나를 보여주는 한 장.</em></h2><p>이력서부터 포트폴리오까지.<br/>필요한 틀을 고르고, 직접 해본 이야기로 채워보세요.</p></div><div className="template-intro-art" aria-hidden="true"><span className="template-back-sheet"/><div className="template-front-sheet"><span>MY STORY</span><strong>안녕하세요,<br/>저는 ______입니다.</strong><i/><i/><i/><span className="paper-pen"><PencilLine size={27}/></span></div><span className="template-floating-label"><Check size={13}/>양식은 준비됐어요</span></div></section>
    <div className="templates-caption"><h2>내 이야기의 첫 번째 틀</h2><span>{DOCUMENT_TEMPLATES.length}개 템플릿 · 자유롭게 수정 가능</span></div><div className="template-grid">{DOCUMENT_TEMPLATES.map((template, index) => <article key={template.id} className={`template-card template-${template.color}`}><button className="template-visual" onClick={() => setPreview(template)} aria-label={`${template.title} 미리 보기`}><span className="template-number">0{index + 1}</span><div className="template-mini-page"><span>J.</span><p>{template.kind}</p><strong>{['경험이 보이는\n나의 이력서', '진심을 전하는\n자기소개서', '과정과 결과로\n말하는 경력', '문제부터 결과까지\n하나의 프로젝트'][index] ?? template.title}</strong><div className="template-mini-rule"/><span className="template-mini-lines"><i/><i/><i/><i/></span></div><span className="preview-on-hover">미리 보기<ArrowUpRight size={16}/></span></button><div className="template-card-content"><div><Tag>{template.kind}</Tag><span className="open-template">EDITABLE</span></div><h3>{template.title}</h3><p>{template.summary}</p><Button onClick={() => setEditing(template)}>이 템플릿으로 작성<ArrowRight size={15}/></Button></div></article>)}</div>
    <section className="template-guidelines"><div><FileText size={21}/><h3>기업 양식에 맞게</h3><p>회사별 문항과 글자 수 제한은 다를 수 있어요. 공고의 안내를 먼저 확인하세요.</p></div><div><Layers3 size={21}/><h3>회사별로 다른 버전</h3><p>같은 경험도 강조할 부분은 달라요. 보관함에서 새 버전을 만들어 다듬어보세요.</p></div><div><LockKeyhole size={21}/><h3>제출한 순간은 그대로</h3><p>지원 공간에서 실제 제출본을 확정하면, 다음 수정과 분리해서 보관해요.</p></div></section><Note>이 템플릿은 합격이나 특정 채용 시스템 통과를 보장하지 않아요. 안내 문구와 빈칸을 실제 경험으로 바꾼 뒤 사용해주세요.</Note>
    {preview && <Modal title={preview.title} description={preview.summary} onClose={() => setPreview(null)} size="wide"><div className="template-preview-wrap"><DocumentPaper doc={{ title: preview.title, kind: preview.kind, text: preview.content }}/></div><div className="form-actions"><Button onClick={() => setPreview(null)}>닫기</Button><Button variant="primary" onClick={() => { setEditing(preview); setPreview(null); }}>이 템플릿으로 작성<ArrowRight size={15}/></Button></div></Modal>}{editing && <DocumentEditor template={editing} close={() => setEditing(null)} onSaved={doc => navigate(`/app/documents?doc=${doc.id}`)}/>}</div>;
}
